### ISSUE TITLE
Broken on Firefox Android

### ISSUE THREAD

**Issue by Thomaseo1** [ken107/read-aloud#62]
This used to work on the Android version of Firefox. Now all I get in options is "auto select" and "on off".
It's broken now on all 3 of my Android devices it appeared to be working on my phone but died after updating to 1.4.10. The other 2 were not updated and were dead before the 1.4.10 rollout. 
Uninstalling and Reinstalling results in same problem continuing.

**Comment by Thomaseo1** [comment]
Here is an example ![screenshot](https://user-images.githubusercontent.com/19182228/47135240-addc5880-d26c-11e8-9782-7de3707737c3.png)

**Comment by ken107** [comment]
Thank you, working on it!

**Comment by ken107** [comment]
48ea9f2
It should work now, please install latest version 1.4.12

**Comment by Thomaseo1** [comment]
Thanks for working on this great app.
Still broken on 2  out of 3 of my Android devices. Broken on an 4.2.2 on clean install of Firefox, hangs and crashes killing even the crash reporter. Shows the same screen as above on my 4.4.2 device. Works on my 5.1 device without any noticeable issue
